var students = ['John', 'Sammy', 'Jaime', 'Mike', 'Jane'];
// console.log(students[0]);
// console.log(students[4]);
// console.log(students.length);
var grades = [90,99,89,100,78];
// console.log(grades[0]);
// console.log(grades[4]);
console.log(grades.length);
console.log(grades[grades.length - 1]);
console.log(grades[grades.length - 4]);